# NumPy Essentials Practice Exercises Overview:


**1. How to import `NumPy` library?** 

In [1]:
# To avoid overwriting the output, please code here 
import numpy as np

**2. Convert the given Python list into NumPy array and check its data type**

In [3]:
list_1 = [1,2,3,4,5]

In [4]:
# To avoid overwriting the output, please code here 
array_1=np.array(list_1)
array_1,type(array_1)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

**3. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [5]:
# To avoid overwriting the output, please code here 
np.arange(0,6)

array([0, 1, 2, 3, 4, 5])

array([0, 1, 2, 3, 4, 5])

**4. Generate an `array of "5" zeros`**

In [6]:
# To avoid overwriting the output, please code here 
np.zeros(5)

array([0., 0., 0., 0., 0.])

array([ 0.,  0.,  0.,  0.,  0.])

**5. Generate the following `matrix`.**

In [7]:
# To avoid overwriting the output, please code here 
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

**6. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [31]:
# To avoid overwriting the output, please code here 
a=np.ones(5)
arr_2 = np.array(a)
print(f'{arr_2}')

[1. 1. 1. 1. 1.]


[ 1.  1.  1.  1.  1.]


**7. Generate an array of "5" tens.**

In [32]:
# To avoid overwriting the output, please code here 
np.ones(5)*10

array([10., 10., 10., 10., 10.])

array([ 10.,  10.,  10.,  10.,  10.])

**8. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [37]:
# To avoid overwriting the output, please code here 
x = np.arange(50,100)
x[2: :2]


array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

In [38]:
#or 
start=50
end=100
np.arange(start+2,end,2)

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

**9. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [39]:
# To avoid overwriting the output, please code here 
np.linspace(0,1,10,retstep=True)

(array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 0.1111111111111111)

(array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
         0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ]),
 0.1111111111111111)

**10. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [66]:
# To avoid overwriting the output, please code here 
array_3=np.arange(0,25)
array_3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
# Generating vector array


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [69]:
# To avoid overwriting the output, please code here 
vec_t_o_2d=array_3.reshape(5,5)
vec_t_o_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
# reshape to convert into 2-d


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [70]:
# To avoid overwriting the output, please code here 

array_3.shape =( 5,5 )
array_3


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
# Using shape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**11. How to generate a single random number using NumPy built-in function?**

In [92]:
# To avoid overwriting the output, please code here
np.random.rand(1) 
#np.random.randint(1,100,1)

array([0.64685343])

array([ 0.55509608])

**12. Write a code to generate a 7x5 matrix of 35 random numbers?** <br>
*Notice, there are no ( ) in the output matrix!*

In [72]:
# To avoid overwriting the output, please code here 
np.random.rand(7,5) 

array([[0.03368515, 0.74660333, 0.32190898, 0.19863302, 0.82237217],
       [0.37398222, 0.18538017, 0.7652135 , 0.62590897, 0.89942462],
       [0.86908131, 0.10581841, 0.41971604, 0.65193056, 0.02155853],
       [0.24484561, 0.22029445, 0.09617132, 0.80821502, 0.14690962],
       [0.75726613, 0.56404879, 0.83264341, 0.22114335, 0.9796353 ],
       [0.75484182, 0.65549287, 0.05970525, 0.02506419, 0.74789858],
       [0.49456598, 0.85004551, 0.61725171, 0.90603703, 0.51145153]])

[[ 0.99598801  0.07546767  0.17484793  0.25229956  0.4693597 ]
 [ 0.5591561   0.5007227   0.93630239  0.48747691  0.78658124]
 [ 0.98923838  0.04124599  0.71326198  0.51252888  0.36130539]
 [ 0.11558779  0.52914213  0.31134907  0.8047612   0.25759207]
 [ 0.87331331  0.77104413  0.960445    0.1732589   0.83339285]
 [ 0.99839604  0.78268012  0.66487603  0.14509928  0.05670129]
 [ 0.15932364  0.848172    0.51343887  0.06309231  0.29250649]]


**13. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [73]:
# To avoid overwriting the output, please code here 
np.eye(5)*5

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

array([[ 5.,  0.,  0.,  0.,  0.],
       [ 0.,  5.,  0.,  0.,  0.],
       [ 0.,  0.,  5.,  0.,  0.],
       [ 0.,  0.,  0.,  5.,  0.],
       [ 0.,  0.,  0.,  0.,  5.]])

**14. Generate the follow matrix "array_2d" and replicate the provided outputs.**

In [86]:
#18a:
# To avoid overwriting the output, please code here 
array_2d = np.arange(0,30).reshape(6,5)
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

**15. Can you calculate the sum of all the numbers in array_2d?**

In [87]:
# To avoid overwriting the output, please code here 
array_2d.sum()

435

435

**16. Calculate sum of all the rows and columns in array_2d.**

In [88]:
# To avoid overwriting the output, please code here 
print("Row sum:", array_2d.sum(axis=1))
print("Columns sum:", array_2d.sum(axis=0))

Row sum: [ 10  35  60  85 110 135]
Columns sum: [75 81 87 93 99]


Row sum: [ 10  35  60  85 110 135]
Columns sum: [75 81 87 93 99]


**17. Calculate the standard deviation of the values in array_2d.**

In [89]:
# To avoid overwriting the output, please code here 
array_2d.std()

8.65544144839919

8.6554414483991895